# Generated by Django 4.0.5 on 2022-07-06 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apodo', models.CharField(max_length=30)),
                ('edad', models.IntegerField()),
                ('fecha_ingreso', models.DateField(null=True)),
            ],
        ),
    ]
