# Generated by Django 4.0.5 on 2022-07-06 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mascota',
            old_name='apodo',
            new_name='nombre',
        ),
    ]
