# Generated by Django 4.0.5 on 2022-06-29 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desafio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prueba',
            new_name='Perro',
        ),
    ]
