# Generated by Django 4.0.5 on 2022-07-04 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desafio', '0003_gato'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gato',
        ),
    ]
